import type {
  Booking,
  Destination,
  Operator,
  Review,
  Tour,
  Vehicle,
} from "@/types";

const unsplash = (id: string) =>
  `https://images.unsplash.com/photo-${id}?q=80&w=1600&auto=format&fit=crop`;

const stockVideo = "https://www.youtube.com/embed/aqz-KE-bpKQ";

export const categories = [
  "Luxury",
  "Adventure",
  "Culture",
  "Wellness",
  "Sports",
  "Medical",
] as const;

export const mockOperators: Operator[] = [
  {
    id: "op-001",
    name: "Dune & Sea Collective",
    rating: 4.9,
    yearsActive: 12,
    responseTime: "Under 1 hour",
    languages: ["English", "Arabic", "French"],
    topBadge: "Elite Desert Guides",
  },
  {
    id: "op-002",
    name: "Oasis Luxe Journeys",
    rating: 4.8,
    yearsActive: 8,
    responseTime: "Under 2 hours",
    languages: ["English", "Italian"],
    topBadge: "Premium Partner",
  },
  {
    id: "op-003",
    name: "Heritage Trails Co.",
    rating: 4.7,
    yearsActive: 15,
    responseTime: "Same day",
    languages: ["English", "Spanish", "Arabic"],
    topBadge: "Cultural Experts",
  },
];

export const mockTours: Tour[] = [
  {
    id: "tour-001",
    slug: "royal-dune-retreat",
    title: "Royal Dune Retreat",
    location: "Al Khurais Dunes",
    region: "Western Desert",
    durationDays: 3,
    groupSize: "Up to 8 guests",
    difficulty: "Easy",
    priceFrom: 1680,
    rating: 4.9,
    reviewsCount: 214,
    category: "Luxury",
    description:
      "Three nights in a private dune sanctuary with chef-led dinners, stargazing rituals, and concierge-curated spa moments under a canvas suite.",
    videoUrl: stockVideo,
    highlights: [
      "Sunset dune dining with private chef",
      "Stargazing lounge with telescope",
      "Luxury camp suites with spa rituals",
    ],
    includes: ["Private guide", "Premium tent suite", "All meals"],
    gradient: "from-[#f8e2bd] via-[#f6d2a3] to-[#e8b98b]",
    gallery: [
      "from-[#f7d5a6] to-[#e9b07e]",
      "from-[#f0d7b2] to-[#dba27b]",
      "from-[#f4d9ac] to-[#e6b987]",
      "from-[#f8e4bf] to-[#e8c09a]",
    ],
    images: [
      unsplash("1542401886-65d6c61db217"),
      unsplash("1518684079-3c830dcef090"),
      unsplash("1469854523086-cc02fe5d8800"),
    ],
    tags: ["Private", "All-inclusive", "Top rated"],
    operatorId: "op-001",
  },
  {
    id: "tour-002",
    slug: "oasis-wellness-sanctuary",
    title: "Oasis Wellness Sanctuary",
    location: "Al Maha Springs",
    region: "Eastern Oasis",
    durationDays: 5,
    groupSize: "Up to 6 guests",
    difficulty: "Easy",
    priceFrom: 2350,
    rating: 4.8,
    reviewsCount: 162,
    category: "Wellness",
    description:
      "A five-day reset of breathwork, thermal pools, and chef-built nutrition guided by a private wellness concierge at a hidden oasis villa.",
    videoUrl: stockVideo,
    highlights: [
      "Morning breathwork with desert vistas",
      "Thermal mineral pools and sound bath",
      "Locally curated wellness cuisine",
    ],
    includes: ["Spa program", "Oasis villa", "Wellness concierge"],
    gradient: "from-[#efe6d6] via-[#e7d2bb] to-[#d6bfa5]",
    gallery: [
      "from-[#efe6d6] to-[#dcc2a4]",
      "from-[#f1dfc6] to-[#d7b395]",
      "from-[#f3e6d2] to-[#d6b79a]",
    ],
    images: [
      unsplash("1571896349842-33c89424de2d"),
      unsplash("1540555700478-4be289fbecef"),
      unsplash("1582719508461-905c673771fd"),
    ],
    tags: ["Wellness", "Slow travel"],
    operatorId: "op-002",
  },
  {
    id: "tour-003",
    slug: "heritage-city-soiree",
    title: "Heritage City Soiree",
    location: "Old Souq Quarter",
    region: "Coastal City",
    durationDays: 2,
    groupSize: "Up to 10 guests",
    difficulty: "Easy",
    priceFrom: 980,
    rating: 4.7,
    reviewsCount: 198,
    category: "Culture",
    description:
      "Two days behind the velvet rope of the old quarter — private museum access, master artisans, and a rooftop tasting menu at golden hour.",
    videoUrl: stockVideo,
    highlights: [
      "Private heritage museum access",
      "Craft atelier workshop",
      "Rooftop evening tasting menu",
    ],
    includes: ["Cultural host", "VIP access", "Curated dining"],
    gradient: "from-[#f2ddc5] via-[#eac7a6] to-[#d9ad8b]",
    gallery: [
      "from-[#f1d7b9] to-[#d9a98d]",
      "from-[#f3ddc3] to-[#d7b291]",
      "from-[#f4e2cb] to-[#d6b191]",
    ],
    images: [
      unsplash("1539037116277-4db20889f2d4"),
      unsplash("1551918120-9739cb430c6d"),
      unsplash("1564507592333-c60657eea523"),
    ],
    tags: ["Iconic", "Curated"],
    operatorId: "op-003",
  },
  {
    id: "tour-004",
    slug: "wadi-adventure-escape",
    title: "Wadi Adventure Escape",
    location: "Wadi Al Noor",
    region: "Mountain Oasis",
    durationDays: 4,
    groupSize: "Up to 12 guests",
    difficulty: "Moderate",
    priceFrom: 1450,
    rating: 4.6,
    reviewsCount: 142,
    category: "Adventure",
    description:
      "Four days of canyon hikes, kayak sunrises, and cliffside lodging — guided by an expedition team that knows every hidden pool and ridgeline.",
    videoUrl: stockVideo,
    highlights: [
      "Guided canyon hikes",
      "Kayak sunrise experience",
      "Cliffside luxury lodge",
    ],
    includes: ["Adventure guide", "Luxury lodge", "Transfers"],
    gradient: "from-[#f2e0c3] via-[#e6c8a2] to-[#cc9a7a]",
    gallery: [
      "from-[#f2e0c3] to-[#d4a883]",
      "from-[#f1d7b4] to-[#c6906f]",
      "from-[#f0dabc] to-[#d1a07f]",
    ],
    images: [
      unsplash("1551632811-561732d1e306"),
      unsplash("1486520299386-6d106b22014b"),
      unsplash("1502780402662-acc01917ddd2"),
    ],
    tags: ["Active", "Nature"],
    operatorId: "op-001",
  },
  {
    id: "tour-005",
    slug: "coastal-luxury-cruise",
    title: "Coastal Luxury Cruise",
    location: "Pearl Coast",
    region: "Northern Shore",
    durationDays: 3,
    groupSize: "Up to 16 guests",
    difficulty: "Easy",
    priceFrom: 1880,
    rating: 4.9,
    reviewsCount: 176,
    category: "Luxury",
    description:
      "Three days aboard a private catamaran along the Pearl Coast, with chef-led seafood tastings, snorkel coves, and golden-hour photography stops.",
    videoUrl: stockVideo,
    highlights: [
      "Private catamaran charter",
      "Chef-led seafood tasting",
      "Golden hour photography",
    ],
    includes: ["Captain & crew", "Gourmet dining", "Snorkeling kit"],
    gradient: "from-[#f1e5d1] via-[#e1c8a8] to-[#caa07c]",
    gallery: [
      "from-[#f1e5d1] to-[#d2b08d]",
      "from-[#f0dbc4] to-[#c69a78]",
      "from-[#f4e7d3] to-[#d3b392]",
    ],
    images: [
      unsplash("1567515004624-219c11d31f2e"),
      unsplash("1540541338287-41700207dee6"),
      unsplash("1500627964684-141351970a7f"),
    ],
    tags: ["Yacht", "Signature"],
    operatorId: "op-002",
  },
  {
    id: "tour-006",
    slug: "wildlife-safari-reserve",
    title: "Wildlife Safari Reserve",
    location: "Al Reem Reserve",
    region: "Northern Plains",
    durationDays: 4,
    groupSize: "Up to 10 guests",
    difficulty: "Moderate",
    priceFrom: 1520,
    rating: 4.7,
    reviewsCount: 134,
    category: "Adventure",
    description:
      "Four days tracking oryx, gazelles, and night-roaming carnivores with a private ranger team at an eco-luxe lodge inside the Al Reem reserve.",
    videoUrl: stockVideo,
    highlights: [
      "Private wildlife tracker",
      "Sustainable lodge stays",
      "Sunrise 4x4 safari",
    ],
    includes: ["Safari guide", "Eco lodge", "Daily excursions"],
    gradient: "from-[#f4dfc1] via-[#e3c7a5] to-[#c79b7e]",
    gallery: [
      "from-[#f4dfc1] to-[#d0a482]",
      "from-[#f0d3ae] to-[#c0916d]",
      "from-[#f3dec3] to-[#d0a784]",
    ],
    images: [
      unsplash("1547036967-23d11aacaee0"),
      unsplash("1535941339077-2dd1c7963098"),
      unsplash("1551845041-63e8e76836ea"),
    ],
    tags: ["Eco", "Private ranger"],
    operatorId: "op-003",
  },
  {
    id: "tour-007",
    slug: "pearl-coast-padel-retreat",
    title: "Pearl Coast Padel Retreat",
    location: "Pearl Coast Club",
    region: "Northern Shore",
    durationDays: 3,
    groupSize: "Up to 6 guests",
    difficulty: "Moderate",
    priceFrom: 1180,
    rating: 4.7,
    reviewsCount: 88,
    category: "Sports",
    description:
      "Three days of padel clinics with pro coaches, seaside recovery sessions, and curated dinners — built for travelers who train and unwind in the same breath.",
    videoUrl: stockVideo,
    highlights: [
      "Daily coaching with touring pros",
      "Beachside cryotherapy and stretch",
      "Performance-focused tasting menus",
    ],
    includes: ["Court time", "Pro coach", "Recovery program"],
    gradient: "from-[#f3e2c4] via-[#e0c39b] to-[#c79c75]",
    gallery: [
      "from-[#f3e2c4] to-[#d0a884]",
      "from-[#f1dab8] to-[#c8956b]",
      "from-[#f4e6d0] to-[#d3ad84]",
    ],
    images: [
      unsplash("1554068865-24cecd4e34cd"),
      unsplash("1517649763962-0c623066013b"),
      unsplash("1452626038306-9aae5e071dd3"),
    ],
    tags: ["Active", "Performance"],
    operatorId: "op-002",
  },
  {
    id: "tour-008",
    slug: "al-maha-recovery-sanctuary",
    title: "Al Maha Recovery Sanctuary",
    location: "Al Maha Medical Spa",
    region: "Eastern Oasis",
    durationDays: 7,
    groupSize: "Up to 4 guests",
    difficulty: "Easy",
    priceFrom: 2980,
    rating: 4.9,
    reviewsCount: 64,
    category: "Medical",
    description:
      "A seven-day medical-tourism program with on-staff physicians, physiotherapy, IV restoration, and a structured sleep protocol — designed for full recalibration.",
    videoUrl: stockVideo,
    highlights: [
      "Physician-led baseline assessment",
      "Daily physiotherapy and IV therapy",
      "Structured sleep and circadian program",
    ],
    includes: ["Resident physician", "Private suite", "All therapies"],
    gradient: "from-[#efe5d4] via-[#dfc8a8] to-[#c4a385]",
    gallery: [
      "from-[#efe5d4] to-[#cfa97f]",
      "from-[#f0dec5] to-[#c69770]",
      "from-[#f4e7d3] to-[#d3ad84]",
    ],
    images: [
      unsplash("1540555700478-4be289fbecef"),
      unsplash("1571896349842-33c89424de2d"),
      unsplash("1544161515-4ab6ce6db874"),
    ],
    tags: ["Medical", "Recovery"],
    operatorId: "op-002",
  },
];

export const mockDestinations: Destination[] = [
  {
    id: "dest-001",
    name: "Al Maha",
    country: "Qatar",
    toursCount: 12,
    gradient: "from-[#f2ddc5] to-[#d6b08f]",
    blurb: "Desert oasis with luxury lodges and wellness sanctuaries.",
    images: [
      unsplash("1542401886-65d6c61db217"),
      unsplash("1518684079-3c830dcef090"),
      unsplash("1469854523086-cc02fe5d8800"),
    ],
    priceFrom: 1680,
    rating: 4.9,
    tags: ["Desert", "Luxury"],
  },
  {
    id: "dest-002",
    name: "Pearl Coast",
    country: "Qatar",
    toursCount: 8,
    gradient: "from-[#f4e6d2] to-[#caa17f]",
    blurb: "Coastal escapes with private charters and serene beaches.",
    images: [
      unsplash("1567515004624-219c11d31f2e"),
      unsplash("1540541338287-41700207dee6"),
      unsplash("1500627964684-141351970a7f"),
    ],
    priceFrom: 1880,
    rating: 4.8,
    tags: ["Coastal", "Yacht"],
  },
  {
    id: "dest-003",
    name: "Old Souq",
    country: "Qatar",
    toursCount: 10,
    gradient: "from-[#f0d8bc] to-[#c79775]",
    blurb: "Heritage markets, artisan ateliers, and historic charm.",
    images: [
      unsplash("1539037116277-4db20889f2d4"),
      unsplash("1551918120-9739cb430c6d"),
      unsplash("1564507592333-c60657eea523"),
    ],
    priceFrom: 980,
    rating: 4.7,
    tags: ["Culture", "Heritage"],
  },
  {
    id: "dest-004",
    name: "Wadi Al Noor",
    country: "Qatar",
    toursCount: 7,
    gradient: "from-[#f1e0c6] to-[#c89b79]",
    blurb: "Hidden valleys with adventure trails and canyon escapes.",
    images: [
      unsplash("1551632811-561732d1e306"),
      unsplash("1486520299386-6d106b22014b"),
      unsplash("1502780402662-acc01917ddd2"),
    ],
    priceFrom: 1450,
    rating: 4.6,
    tags: ["Adventure", "Nature"],
  },
  {
    id: "dest-005",
    name: "Al Reem",
    country: "Qatar",
    toursCount: 6,
    gradient: "from-[#f3dec3] to-[#cda07c]",
    blurb: "Wildlife reserve with exclusive safari experiences.",
    images: [
      unsplash("1547036967-23d11aacaee0"),
      unsplash("1535941339077-2dd1c7963098"),
      unsplash("1551845041-63e8e76836ea"),
    ],
    priceFrom: 1520,
    rating: 4.7,
    tags: ["Wildlife", "Eco"],
  },
];

export const mockVehicles: Vehicle[] = [
  {
    id: "veh-101",
    name: "Economy Sedan",
    fleetCategory: "Economy",
    capacity: 4,
    luggage: "2 large + 2 carry-ons",
    priceFrom: 60,
    halfDayPrice: 80,
    fullDayPrice: 150,
    extraHourPrice: 25,
    transferPrice: 60,
    features: ["AC", "Bottled water", "English driver"],
    gradient: "from-[#f3e4cf] to-[#d9b793]",
  },
  {
    id: "veh-102",
    name: "Economy Van",
    fleetCategory: "Economy",
    capacity: 6,
    luggage: "5 medium",
    priceFrom: 85,
    halfDayPrice: 110,
    fullDayPrice: 200,
    extraHourPrice: 35,
    transferPrice: 85,
    features: ["AC", "USB charging", "Spacious cabin"],
    gradient: "from-[#f0dbc4] to-[#cba17c]",
  },
  {
    id: "veh-201",
    name: "Executive SUV",
    fleetCategory: "Premium",
    capacity: 4,
    luggage: "3 large + 2 carry-ons",
    priceFrom: 120,
    halfDayPrice: 140,
    fullDayPrice: 240,
    extraHourPrice: 40,
    transferPrice: 120,
    features: ["Leather interior", "Wi-Fi", "Refreshments"],
    gradient: "from-[#f3e0c5] to-[#d2a982]",
  },
  {
    id: "veh-202",
    name: "Luxury Van",
    fleetCategory: "Premium",
    capacity: 8,
    luggage: "8 medium",
    priceFrom: 160,
    halfDayPrice: 180,
    fullDayPrice: 320,
    extraHourPrice: 55,
    transferPrice: 160,
    features: ["Panoramic roof", "USB-C ports", "Climate control"],
    gradient: "from-[#efd9bf] to-[#c79a78]",
  },
  {
    id: "veh-301",
    name: "VIP Sedan",
    fleetCategory: "VIP",
    capacity: 2,
    luggage: "2 large",
    priceFrom: 140,
    halfDayPrice: 160,
    fullDayPrice: 280,
    extraHourPrice: 45,
    transferPrice: 140,
    features: ["Privacy glass", "Onboard concierge", "Ambient lighting"],
    gradient: "from-[#f4e5d0] to-[#cfac88]",
  },
  {
    id: "veh-302",
    name: "VIP Limousine",
    fleetCategory: "VIP",
    capacity: 4,
    luggage: "4 large",
    priceFrom: 220,
    halfDayPrice: 260,
    fullDayPrice: 460,
    extraHourPrice: 80,
    transferPrice: 220,
    features: ["Champagne service", "Private chauffeur", "Privacy partition"],
    gradient: "from-[#f0dabb] to-[#c79873]",
  },
];

export const mockBookings: Booking[] = [
  {
    id: "bk-001",
    tourId: "tour-001",
    tourTitle: "Royal Dune Retreat",
    date: "2026-06-18",
    guests: 2,
    status: "Upcoming",
    price: 3360,
    reference: "ORYX-1024",
    gradient: "from-[#f7e3c2] to-[#d9b08b]",
  },
  {
    id: "bk-002",
    tourId: "tour-003",
    tourTitle: "Heritage City Soiree",
    date: "2026-05-04",
    guests: 4,
    status: "Completed",
    price: 3920,
    reference: "ORYX-0981",
    gradient: "from-[#f3e0c8] to-[#c99f7b]",
  },
  {
    id: "bk-003",
    tourId: "tour-004",
    tourTitle: "Wadi Adventure Escape",
    date: "2026-04-16",
    guests: 3,
    status: "Cancelled",
    price: 4350,
    reference: "ORYX-0876",
    gradient: "from-[#f1dcc1] to-[#c99575]",
  },
];

export const mockReviews: Review[] = [
  {
    id: "rev-001",
    name: "Amina K.",
    rating: 5,
    date: "2026-02-11",
    content:
      "Every detail felt effortless. The sunset dining and stargazing lounge were unforgettable.",
  },
  {
    id: "rev-002",
    name: "Luca R.",
    rating: 5,
    date: "2026-01-22",
    content:
      "Impeccable service and a luxurious camp suite. The private guide made it personal.",
  },
  {
    id: "rev-003",
    name: "Sara M.",
    rating: 4,
    date: "2025-12-30",
    content:
      "Great itinerary and a calm atmosphere. The wellness rituals were the highlight.",
  },
];
