import type {
  Booking,
  Destination,
  Operator,
  Review,
  Tour,
  Vehicle,
} from "@/types";

export const categories = [
  "Adventure",
  "Luxury",
  "Culture",
  "Desert",
  "City",
  "Wellness",
  "Wildlife",
] as const;

export const mockOperators: Operator[] = [
  {
    id: "op-001",
    name: "Dune & Sea Collective",
    rating: 4.9,
    yearsActive: 12,
    responseTime: "Under 1 hour",
    languages: ["English", "Arabic", "French"],
    topBadge: "Elite Desert Guides",
  },
  {
    id: "op-002",
    name: "Oasis Luxe Journeys",
    rating: 4.8,
    yearsActive: 8,
    responseTime: "Under 2 hours",
    languages: ["English", "Italian"],
    topBadge: "Premium Partner",
  },
  {
    id: "op-003",
    name: "Heritage Trails Co.",
    rating: 4.7,
    yearsActive: 15,
    responseTime: "Same day",
    languages: ["English", "Spanish", "Arabic"],
    topBadge: "Cultural Experts",
  },
];

export const mockTours: Tour[] = [
  {
    id: "tour-001",
    slug: "royal-dune-retreat",
    title: "Royal Dune Retreat",
    location: "Al Khurais Dunes",
    region: "Western Desert",
    durationDays: 3,
    groupSize: "Up to 8 guests",
    difficulty: "Easy",
    priceFrom: 1680,
    rating: 4.9,
    reviewsCount: 214,
    category: "Luxury",
    highlights: [
      "Sunset dune dining with private chef",
      "Stargazing lounge with telescope",
      "Luxury camp suites with spa rituals",
    ],
    includes: ["Private guide", "Premium tent suite", "All meals"],
    gradient: "from-[#f8e2bd] via-[#f6d2a3] to-[#e8b98b]",
    gallery: [
      "from-[#f7d5a6] to-[#e9b07e]",
      "from-[#f0d7b2] to-[#dba27b]",
      "from-[#f4d9ac] to-[#e6b987]",
      "from-[#f8e4bf] to-[#e8c09a]",
    ],
    tags: ["Private", "All-inclusive", "Top rated"],
    operatorId: "op-001",
  },
  {
    id: "tour-002",
    slug: "oasis-wellness-sanctuary",
    title: "Oasis Wellness Sanctuary",
    location: "Al Maha Springs",
    region: "Eastern Oasis",
    durationDays: 5,
    groupSize: "Up to 6 guests",
    difficulty: "Easy",
    priceFrom: 2350,
    rating: 4.8,
    reviewsCount: 162,
    category: "Wellness",
    highlights: [
      "Morning breathwork with desert vistas",
      "Thermal mineral pools and sound bath",
      "Locally curated wellness cuisine",
    ],
    includes: ["Spa program", "Oasis villa", "Wellness concierge"],
    gradient: "from-[#efe6d6] via-[#e7d2bb] to-[#d6bfa5]",
    gallery: [
      "from-[#efe6d6] to-[#dcc2a4]",
      "from-[#f1dfc6] to-[#d7b395]",
      "from-[#f3e6d2] to-[#d6b79a]",
    ],
    tags: ["Wellness", "Slow travel"],
    operatorId: "op-002",
  },
  {
    id: "tour-003",
    slug: "heritage-city-soiree",
    title: "Heritage City Soiree",
    location: "Old Souq Quarter",
    region: "Coastal City",
    durationDays: 2,
    groupSize: "Up to 10 guests",
    difficulty: "Easy",
    priceFrom: 980,
    rating: 4.7,
    reviewsCount: 198,
    category: "Culture",
    highlights: [
      "Private heritage museum access",
      "Craft atelier workshop",
      "Rooftop evening tasting menu",
    ],
    includes: ["Cultural host", "VIP access", "Curated dining"],
    gradient: "from-[#f2ddc5] via-[#eac7a6] to-[#d9ad8b]",
    gallery: [
      "from-[#f1d7b9] to-[#d9a98d]",
      "from-[#f3ddc3] to-[#d7b291]",
      "from-[#f4e2cb] to-[#d6b191]",
    ],
    tags: ["Iconic", "Curated"],
    operatorId: "op-003",
  },
  {
    id: "tour-004",
    slug: "wadi-adventure-escape",
    title: "Wadi Adventure Escape",
    location: "Wadi Al Noor",
    region: "Mountain Oasis",
    durationDays: 4,
    groupSize: "Up to 12 guests",
    difficulty: "Moderate",
    priceFrom: 1450,
    rating: 4.6,
    reviewsCount: 142,
    category: "Adventure",
    highlights: [
      "Guided canyon hikes",
      "Kayak sunrise experience",
      "Cliffside luxury lodge",
    ],
    includes: ["Adventure guide", "Luxury lodge", "Transfers"],
    gradient: "from-[#f2e0c3] via-[#e6c8a2] to-[#cc9a7a]",
    gallery: [
      "from-[#f2e0c3] to-[#d4a883]",
      "from-[#f1d7b4] to-[#c6906f]",
      "from-[#f0dabc] to-[#d1a07f]",
    ],
    tags: ["Active", "Nature"],
    operatorId: "op-001",
  },
  {
    id: "tour-005",
    slug: "coastal-luxury-cruise",
    title: "Coastal Luxury Cruise",
    location: "Pearl Coast",
    region: "Northern Shore",
    durationDays: 3,
    groupSize: "Up to 16 guests",
    difficulty: "Easy",
    priceFrom: 1880,
    rating: 4.9,
    reviewsCount: 176,
    category: "Luxury",
    highlights: [
      "Private catamaran charter",
      "Chef-led seafood tasting",
      "Golden hour photography",
    ],
    includes: ["Captain & crew", "Gourmet dining", "Snorkeling kit"],
    gradient: "from-[#f1e5d1] via-[#e1c8a8] to-[#caa07c]",
    gallery: [
      "from-[#f1e5d1] to-[#d2b08d]",
      "from-[#f0dbc4] to-[#c69a78]",
      "from-[#f4e7d3] to-[#d3b392]",
    ],
    tags: ["Yacht", "Signature"],
    operatorId: "op-002",
  },
  {
    id: "tour-006",
    slug: "wildlife-safari-reserve",
    title: "Wildlife Safari Reserve",
    location: "Al Reem Reserve",
    region: "Northern Plains",
    durationDays: 4,
    groupSize: "Up to 10 guests",
    difficulty: "Moderate",
    priceFrom: 1520,
    rating: 4.7,
    reviewsCount: 134,
    category: "Wildlife",
    highlights: [
      "Private wildlife tracker",
      "Sustainable lodge stays",
      "Sunrise 4x4 safari",
    ],
    includes: ["Safari guide", "Eco lodge", "Daily excursions"],
    gradient: "from-[#f4dfc1] via-[#e3c7a5] to-[#c79b7e]",
    gallery: [
      "from-[#f4dfc1] to-[#d0a482]",
      "from-[#f0d3ae] to-[#c0916d]",
      "from-[#f3dec3] to-[#d0a784]",
    ],
    tags: ["Eco", "Private ranger"],
    operatorId: "op-003",
  },
];

export const mockDestinations: Destination[] = [
  {
    id: "dest-001",
    name: "Al Maha",
    country: "Qatar",
    toursCount: 12,
    gradient: "from-[#f2ddc5] to-[#d6b08f]",
    blurb: "Desert oasis with luxury lodges and wellness sanctuaries.",
  },
  {
    id: "dest-002",
    name: "Pearl Coast",
    country: "Qatar",
    toursCount: 8,
    gradient: "from-[#f4e6d2] to-[#caa17f]",
    blurb: "Coastal escapes with private charters and serene beaches.",
  },
  {
    id: "dest-003",
    name: "Old Souq",
    country: "Qatar",
    toursCount: 10,
    gradient: "from-[#f0d8bc] to-[#c79775]",
    blurb: "Heritage markets, artisan ateliers, and historic charm.",
  },
  {
    id: "dest-004",
    name: "Wadi Al Noor",
    country: "Qatar",
    toursCount: 7,
    gradient: "from-[#f1e0c6] to-[#c89b79]",
    blurb: "Hidden valleys with adventure trails and canyon escapes.",
  },
  {
    id: "dest-005",
    name: "Al Reem",
    country: "Qatar",
    toursCount: 6,
    gradient: "from-[#f3dec3] to-[#cda07c]",
    blurb: "Wildlife reserve with exclusive safari experiences.",
  },
];

export const mockVehicles: Vehicle[] = [
  {
    id: "veh-001",
    name: "Executive SUV",
    capacity: 4,
    luggage: "3 large + 2 carry-ons",
    priceFrom: 120,
    features: ["Leather interior", "Wi-Fi", "Refreshments"],
    gradient: "from-[#f3e4cf] to-[#d5b190]",
  },
  {
    id: "veh-002",
    name: "Luxury Van",
    capacity: 8,
    luggage: "8 medium",
    priceFrom: 180,
    features: ["Panoramic roof", "USB-C ports", "Climate control"],
    gradient: "from-[#f0dbc4] to-[#c79a78]",
  },
  {
    id: "veh-003",
    name: "VIP Sedan",
    capacity: 2,
    luggage: "2 large",
    priceFrom: 95,
    features: ["Privacy glass", "On-board concierge", "Ambient lighting"],
    gradient: "from-[#f4e5d0] to-[#cfac88]",
  },
];

export const mockBookings: Booking[] = [
  {
    id: "bk-001",
    tourId: "tour-001",
    tourTitle: "Royal Dune Retreat",
    date: "2026-06-18",
    guests: 2,
    status: "Upcoming",
    price: 3360,
    reference: "ORYX-1024",
    gradient: "from-[#f7e3c2] to-[#d9b08b]",
  },
  {
    id: "bk-002",
    tourId: "tour-003",
    tourTitle: "Heritage City Soiree",
    date: "2026-05-04",
    guests: 4,
    status: "Completed",
    price: 3920,
    reference: "ORYX-0981",
    gradient: "from-[#f3e0c8] to-[#c99f7b]",
  },
  {
    id: "bk-003",
    tourId: "tour-004",
    tourTitle: "Wadi Adventure Escape",
    date: "2026-04-16",
    guests: 3,
    status: "Cancelled",
    price: 4350,
    reference: "ORYX-0876",
    gradient: "from-[#f1dcc1] to-[#c99575]",
  },
];

export const mockReviews: Review[] = [
  {
    id: "rev-001",
    name: "Amina K.",
    rating: 5,
    date: "2026-02-11",
    content:
      "Every detail felt effortless. The sunset dining and stargazing lounge were unforgettable.",
  },
  {
    id: "rev-002",
    name: "Luca R.",
    rating: 5,
    date: "2026-01-22",
    content:
      "Impeccable service and a luxurious camp suite. The private guide made it personal.",
  },
  {
    id: "rev-003",
    name: "Sara M.",
    rating: 4,
    date: "2025-12-30",
    content:
      "Great itinerary and a calm atmosphere. The wellness rituals were the highlight.",
  },
];
